const root = document.getElementById('root')

const grid = document.createElement('div')
grid.setAttribute('class', 'grid')

const img1 = document.createElement('img')
img1.setAttribute('src' , '1.png')
const img2 = document.createElement('img')
img2.setAttribute('src' , '2.png')
const img3 = document.createElement('img')
img3.setAttribute('src' , '3.jpg')
const img4 = document.createElement('img')
img4.setAttribute('src' , '4.jpg')
const img5 = document.createElement('img')
img5.setAttribute('src' , '5.jpg')

grid.appendChild(img1)
grid.appendChild(img2)
grid.appendChild(img3)
grid.appendChild(img4)
grid.appendChild(img5)
root.appendChild(grid)