const root = document.getElementById('root')

const grid = document.createElement('div')
grid.setAttribute('class', 'grid')

const img1 = document.createElement('img')
img1.setAttribute('src' , '1.png')
const img2 = document.createElement('img')
img2.setAttribute('src' , '2.png')
const img3 = document.createElement('img')
img3.setAttribute('src' , '3.jpg')
const img4 = document.createElement('img')
img4.setAttribute('src' , '4.jpg')
const img5 = document.createElement('img')
img5.setAttribute('src' , '5.jpg')
const img6 = document.createElement('img')
img6.setAttribute('src' , '6.jpg')
const img7 = document.createElement('img')
img7.setAttribute('src' , '7.jpg')
const img8 = document.createElement('img')
img8.setAttribute('src' , '8.jpg')
const img9 = document.createElement('img')
img9.setAttribute('src' , '9.jpg')
const img10 = document.createElement('img')
img10.setAttribute('src' , '10.jpg')
const img11 = document.createElement('img')
img11.setAttribute('src' , '11.jpg')
const img12 = document.createElement('img')
img12.setAttribute('src' , '12.jpg')
const img13 = document.createElement('img')
img13.setAttribute('src' , '13.webp')
const img14 = document.createElement('img')
img14.setAttribute('src' , '14.jpg')
const img15 = document.createElement('img')
img15.setAttribute('src' , '15.jpg')
const img16 = document.createElement('img')
img16.setAttribute('src' , '16.jpg')
const img17 = document.createElement('img')
img17.setAttribute('src' , '17.jpg')
const img18 = document.createElement('img')
img18.setAttribute('src' , '18.jpg')

grid.appendChild(img1)
grid.appendChild(img2)
grid.appendChild(img3)
grid.appendChild(img4)
grid.appendChild(img5)
grid.appendChild(img6)
grid.appendChild(img7)
grid.appendChild(img8)
grid.appendChild(img9)
grid.appendChild(img10)
grid.appendChild(img11)
grid.appendChild(img12)
grid.appendChild(img13)
grid.appendChild(img14)
grid.appendChild(img15)
grid.appendChild(img16)
grid.appendChild(img17)
grid.appendChild(img18)
root.appendChild(grid)